refactor: server's Dockerfile to download platform specific grpc_health_probe binaries

diff --git a/server/deploy/Dockerfile b/server/deploy/Dockerfile
--- a/server/deploy/Dockerfile
+++ b/server/deploy/Dockerfile
@@ -1,7 +1,36 @@
 FROM golang:1.16-alpine AS builder
 
-RUN apk --no-cache add ca-certificates && GRPC_HEALTH_PROBE_VERSION=v0.4.2 && \
-  wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
+ENV GRPC_HEALTH_PROBE_VERSION v0.4.2
+
+RUN set -eux; \
+  apkArch="$(apk --print-arch)"; \
+  case "$apkArch" in \
+  'x86_64') \
+  export GOARCH='amd64' GOOS='linux'; \
+  ;; \
+  'armhf') \
+  export GOARCH='arm' GOARM='6' GOOS='linux'; \
+  ;; \
+  'armv7') \
+  export GOARCH='arm' GOARM='7' GOOS='linux'; \
+  ;; \
+  'aarch64') \
+  export GOARCH='arm64' GOOS='linux'; \
+  ;; \
+  'x86') \
+  export GO386='softfloat' GOARCH='386' GOOS='linux'; \
+  ;; \
+  'ppc64le') \
+  export GOARCH='ppc64le' GOOS='linux'; \
+  ;; \
+  's390x') \
+  export GOARCH='s390x' GOOS='linux'; \
+  ;; \
+  *) echo >&2 "error: unsupported architecture '$apkArch' (likely packaging update needed)"; exit 1 ;; \
+  esac; \
+  \
+  URL="https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-${GOOS}-${GOARCH}"; \
+  wget -O /bin/grpc_health_probe "$URL"; \
   chmod +x /bin/grpc_health_probe
 
 WORKDIR /src/
@@ -9,7 +38,7 @@ COPY go.mod .
 COPY go.sum .
 RUN go mod download
 COPY . .
-RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-w -s" -o server cmd/server/main.go
+RUN CGO_ENABLED=0 go build -ldflags "-w -s" -o server cmd/server/main.go
 
 FROM gcr.io/distroless/static:nonroot
 
